version: '3.8'

services:
  web:
    build: .
    command: "flask run --host=0.0.0.0 --port=5000"
    volumes:
      - .:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask-database-zappts-dev
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
volumes:
  postgres_data: