[default]
SQLALCHEMY_TRACK_MODIFICATIONS=false

[development]
SQLALCHEMY_DATABASE_URI="postgresql://postgres:password@localhost/flask-database-zappts-dev"

[production]
SQLALCHEMY_DATABASE_URI="postgresql://postgres:password@localhost/flask-database-zappts"

[testing]
SQLALCHEMY_DATABASE_URI="sqlite://"