"""empty message

Revision ID: 4f91b69d920e
Revises: 
Create Date: 2021-05-31 09:17:12.525672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f91b69d920e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('send_email', sa.String(length=84), nullable=False),
    sa.Column('reference_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letters_email'), 'letters', ['email'], unique=True)
    op.create_index(op.f('ix_letters_send_email'), 'letters', ['send_email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_letters_send_email'), table_name='letters')
    op.drop_index(op.f('ix_letters_email'), table_name='letters')
    op.drop_table('letters')
    # ### end Alembic commands ###
