"""empty message

Revision ID: 7fee63d7919b
Revises: c03d9de81c47
Create Date: 2021-05-31 09:23:40.082849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fee63d7919b'
down_revision = 'c03d9de81c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'letters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'letters', type_='foreignkey')
    op.drop_column('letters', 'user_id')
    # ### end Alembic commands ###
