"""empty message

Revision ID: 97dbd1856d11
Revises: 401b1cda4c73
Create Date: 2021-05-31 10:19:26.470823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dbd1856d11'
down_revision = '401b1cda4c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('letters_user_id_fkey', 'letters', type_='foreignkey')
    op.drop_column('letters', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('letters_user_id_fkey', 'letters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
