"""empty message

Revision ID: c03d9de81c47
Revises: 4f91b69d920e
Create Date: 2021-05-31 09:22:23.224230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03d9de81c47'
down_revision = '4f91b69d920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_letter_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'letter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('letter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_letter_id_fkey', 'users', 'letters', ['letter_id'], ['id'])
    # ### end Alembic commands ###
