"""empty message

Revision ID: c30b47d1034d
Revises: 97dbd1856d11
Create Date: 2021-05-31 10:24:17.083358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30b47d1034d'
down_revision = '97dbd1856d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_letters_email', table_name='letters')
    op.create_index(op.f('ix_letters_email'), 'letters', ['email'], unique=False)
    op.drop_index('ix_letters_send_email', table_name='letters')
    op.create_index(op.f('ix_letters_send_email'), 'letters', ['send_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letters_send_email'), table_name='letters')
    op.create_index('ix_letters_send_email', 'letters', ['send_email'], unique=False)
    op.drop_index(op.f('ix_letters_email'), table_name='letters')
    op.create_index('ix_letters_email', 'letters', ['email'], unique=False)
    # ### end Alembic commands ###
